language: generic

services:
  - docker

before_install:
  - docker build -t navnathd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true navnathd/react-test npm test

after_success:
  - docker build -t navanthd/multi-client ./client
  - docker build -t navanthd/multi-nginx ./nginx
  - docker build -t navanthd/multi-server ./server
  - docker build -t navanthd/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push navanthd/multi-client
  - docker push navanthd/multi-nginx
  - docker push navanthd/multi-server
  - docker push navanthd/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'Multidocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-983207180145'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY







